---
title: "Laborator"
output: html_document
date: "2022-12-08"
---

# Ex1

Fie X o va cu valori in 1, 2, 3, 4 si cu masele 0.2, 0.5, 0.1 si 0.2.

```{r}
# var1
n <- 10000
x <- sample(1:4, n, replace = TRUE, prob = c(0.2, 0.5, 0.1, 0.2))

table(x)/n

# var2
u <- runif(n)

x <- 1 + (u > 0.2) + (u > 0.7) + (u > 0.8)

p_E <- table(x)/n
p_T <- c(0.2, 0.5, 0.1, 0.2)

barplot(rbind(p_E, p_T), 
        beside = TRUE, 
        names.arg = 1:4, 
        legend.text = c("Repartitia esantionului", "Repartitia teoretica"))

```

#Ex2 

Construim o functie care sa genereze un esantion de volum n dintr-o repartitie discreta data. 

```{r}
GenVarDiscrete <- function(n = 10, x = c("H", "T"), p = c(0.5, 0.5), tol = 1e-8){
  lx <- length(x)
  lp <- length(p)
  
  if (lx!=lp){
    stop("Mesaj de eroare!")
  }else if (any(p < 0) | abs(sum(p) - 1) > tol){
    stop("Eroare 2!")
  }
  
  indOrd <- order(p, decreasing = TRUE)
  
  pOrd <- p[indOrd]
  xOrd <- x[indOrd]
  
  pOrdCum <- cumsum(pOrd)
  
  u <- runif(n)
  out <- numeric(n)
  
  for(i in 1:n){
    k <- min(which(u[i] <= pOrdCum))
    
    # k <- sum(u[i] > pOrdCum) + 1
    
    out[i] <- xOrd[k]
  }
  
  return(out)
  
}

# Ex1
n <- 10000
x <- GenVarDiscrete(n, 1:4, c(0.2, 0.5, 0.1, 0.2))

p_E <- table(x)/n
p_T <- c(0.2, 0.5, 0.1, 0.2)

barplot(rbind(p_E, p_T), 
        beside = TRUE, 
        names.arg = 1:4, 
        legend.text = c("Repartitia esantionului", "Repartitia teoretica"))
```

Construim functie care sa afiseze grafic

```{r}
Compar_diag_bare <- function(pX, pT, ...){
  numeX <- names(pX)
  
  barplot(rbind(pX, pT), 
        beside = TRUE, 
        names.arg = numeX, 
        col = c("blue", "red"),
        ylab = "PDF",
        legend.text = c("Repartitia esantionului", "Repartitia teoretica"),
        ...)
}

Compar_diag_bare(p_E, p_T)
```


1. Binomiala 

```{r}
n <- 100000
s <- 10
p <- 0.3

pX <- table(GenVarDiscrete(n, x = 0:s, p = dbinom(0:s, s, p)))/n
pT <- dbinom(as.numeric(names(pX)), s, p)

Compar_diag_bare(pX, pT, main = "Repartitia Binomiala")

dbinom(10, 10, 0.3)
```

2. Geometrica

```{r}
n <- 100000
p <- 0.3

# abs(sum(dgeom(0:100, p)) - 1) > 1e-8


pX <- table(GenVarDiscrete(n, x = 0:100, p = dgeom(0:100, p)))/n
pT <- dgeom(as.numeric(names(pX)), p)

Compar_diag_bare(pX, pT, main = "Repartitia Geometrica")
```

```{r}
gen_geom <- function(n = 100, p = 0.5){
  u <- runif(n)
  
  # x <- floor(log(u)/log(1-p)) + 1
  x <- floor(log(u)/log(1-p))
  
  return(x)
}

# verificare
n <- 100000
p <- 0.3

pX <- table(gen_geom(n,p))/n
pT <- dgeom(as.numeric(names(pX)), p)

Compar_diag_bare(pX, pT)
```

3. Uniforma

```{r}
gen_unif_discret <- function(n = 100, N = 10){
  u <- runif(n)
  
  x <- floor(N*u) + 1
  
  return(x)
}

n <- 100000
N = 10

pX <- table(gen_unif_discret(n,N))/n
pT <- rep(1/N,N)

Compar_diag_bare(pX, pT)
```

4 Binomiala revizuita

```{r}
gen_bin2 <- function(n = 100, size = 10, p = 0.5){
  x <- numeric(n)
  r <- p/(1-p)
  
  for(i in 1:n){
    u <- runif(1)
    
    x[i] <- 0
    
    pb <- (1-p)^size
    Fr <- pb
    
    while (u >= Fr) {
      pb <- (size - x[i])/(x[i] + 1)*r*pb
      Fr <- Fr + pb
      
      x[i] <- x[i] + 1
    }
  }
  
  return(x)
}

# verificare
n <- 100000
s <- 10
p <- 0.3

pX <- table(gen_bin2(n, s, p))/n
pT <- dbinom(as.numeric(names(pX)), s, p)

Compar_diag_bare(pX, pT, main = "Repartitia Binomiala")
```











